---
protocol-key-pair:
  path: {{BINARY_PATH}}/protocol.key
worker-key-pair:
  path: {{BINARY_PATH}}/worker.key
account-key-pair:
  path: {{BINARY_PATH}}/account.key
network-key-pair:
  path: {{BINARY_PATH}}/network.key
db-path: {{DATA_FOLDER}}/db/authorities_db
network-address: /ip4/0.0.0.0/tcp/8080/http
json-rpc-address: 0.0.0.0:9000
metrics-address: 0.0.0.0:9184
admin-interface-port: 1337
consensus-config:
  address: /ip4/127.0.0.1/tcp/8083/http
  db-path: {{DATA_FOLDER}}/db/consensus_db
  internal-worker-address: null
  narwhal-config:
    header_num_of_batches_threshold: 32
    max_header_num_of_batches: 1000
    max_header_delay: 2000ms
    gc_depth: 50
    sync_retry_delay: 5000ms
    sync_retry_nodes: 3
    batch_size: 500000
    max_batch_delay: 100ms
    block_synchronizer:
      range_synchronize_timeout: 30000ms
      certificates_synchronize_timeout: 30000ms
      payload_synchronize_timeout: 30000ms
      payload_availability_timeout: 30000ms
      handler_certificate_deliver_timeout: 30000ms
    consensus_api_grpc:
      socket_addr: /ip4/127.0.0.1/tcp/44579/http
      get_collections_timeout: 5000ms
      remove_collections_timeout: 5000ms
    max_concurrent_requests: 500000
    prometheus_metrics:
      socket_addr: /ip4/127.0.0.1/tcp/33291/http
    network_admin_server:
      primary_network_admin_server_port: 41303
      worker_network_admin_server_base_port: 41669
enable-event-processing: false
p2p-config:
  listen-address: 0.0.0.0:8084
  external-address: /dns/{{DNS_NAME}}/udp/8084
  anemo-config:
    max-concurrent-connections: 0
genesis:
  genesis-file-location: {{BINARY_PATH}}/genesis.blob
authority-store-pruning-config:
  num-latest-epoch-dbs-to-retain: 3
  epoch-db-pruning-period-secs: 3600
  num-epochs-to-retain: 1
  max-checkpoints-in-batch: 5
  max-transactions-in-batch: 1000
  use-range-deletion: true
end-of-epoch-broadcast-channel-capacity: 128
checkpoint-executor-config:
  checkpoint-execution-max-concurrency: 200
  local-execution-timeout-sec: 10
db-checkpoint-config:
  perform-db-checkpoints-at-epoch-end: false
indirect-objects-threshold: 18446744073709551615
metrics:
  push-interval-seconds: 60
  push-url: https://metrics-proxy.{{SUI_NETWORK}}.sui.io:8443/publish/metrics
